/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://openapi-generator.tech
 */

/// ContractDeliverGood : The details of a delivery contract. Includes the type of good, units needed, and the destination.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContractDeliverGood {
    /// The symbol of the trade good to deliver.
    #[serde(rename = "tradeSymbol")]
    pub trade_symbol: String,
    /// The destination where goods need to be delivered.
    #[serde(rename = "destinationSymbol")]
    pub destination_symbol: String,
    /// The number of units that need to be delivered on this contract.
    #[serde(rename = "unitsRequired")]
    pub units_required: i32,
    /// The number of units fulfilled on this contract.
    #[serde(rename = "unitsFulfilled")]
    pub units_fulfilled: i32,
}

impl ContractDeliverGood {
    /// The details of a delivery contract. Includes the type of good, units needed, and the destination.
    pub fn new(trade_symbol: String, destination_symbol: String, units_required: i32, units_fulfilled: i32) -> ContractDeliverGood {
        ContractDeliverGood {
            trade_symbol,
            destination_symbol,
            units_required,
            units_fulfilled,
        }
    }
}


