/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://openapi-generator.tech
 */

/// ShipReactor : The reactor of the ship. The reactor is responsible for powering the ship's systems and weapons.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ShipReactor {
    /// Symbol of the reactor.
    #[serde(rename = "symbol")]
    pub symbol: Symbol,
    /// Name of the reactor.
    #[serde(rename = "name")]
    pub name: String,
    /// Description of the reactor.
    #[serde(rename = "description")]
    pub description: String,
    /// Condition is a range of 0 to 100 where 0 is completely worn out and 100 is brand new.
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<i32>,
    /// The amount of power provided by this reactor. The more power a reactor provides to the ship, the lower the cooldown it gets when using a module or mount that taxes the ship's power.
    #[serde(rename = "powerOutput")]
    pub power_output: i32,
    #[serde(rename = "requirements")]
    pub requirements: Box<crate::models::ShipRequirements>,
}

impl ShipReactor {
    /// The reactor of the ship. The reactor is responsible for powering the ship's systems and weapons.
    pub fn new(symbol: Symbol, name: String, description: String, power_output: i32, requirements: crate::models::ShipRequirements) -> ShipReactor {
        ShipReactor {
            symbol,
            name,
            description,
            condition: None,
            power_output,
            requirements: Box::new(requirements),
        }
    }
}

/// Symbol of the reactor.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Symbol {
    #[serde(rename = "REACTOR_SOLAR_I")]
    SolarI,
    #[serde(rename = "REACTOR_FUSION_I")]
    FusionI,
    #[serde(rename = "REACTOR_FISSION_I")]
    FissionI,
    #[serde(rename = "REACTOR_CHEMICAL_I")]
    ChemicalI,
    #[serde(rename = "REACTOR_ANTIMATTER_I")]
    AntimatterI,
}

impl Default for Symbol {
    fn default() -> Symbol {
        Self::SolarI
    }
}

