/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Faction : Faction details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Faction {
    #[serde(rename = "symbol")]
    pub symbol: models::FactionSymbol,
    /// Name of the faction.
    #[serde(rename = "name")]
    pub name: String,
    /// Description of the faction.
    #[serde(rename = "description")]
    pub description: String,
    /// The waypoint in which the faction's HQ is located in.
    #[serde(rename = "headquarters")]
    pub headquarters: String,
    /// List of traits that define this faction.
    #[serde(rename = "traits")]
    pub traits: Vec<models::FactionTrait>,
    /// Whether or not the faction is currently recruiting new agents.
    #[serde(rename = "isRecruiting")]
    pub is_recruiting: bool,
}

impl Faction {
    /// Faction details.
    pub fn new(symbol: models::FactionSymbol, name: String, description: String, headquarters: String, traits: Vec<models::FactionTrait>, is_recruiting: bool) -> Faction {
        Faction {
            symbol,
            name,
            description,
            headquarters,
            traits,
            is_recruiting,
        }
    }
}

